# Generated by Django 4.2.6 on 2023-10-22 13:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('trip_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('client_type', models.CharField(choices=[('B2B', 'Business-to-Business (B2B)'), ('DIRECT', 'Direct Client')], default='B2B', max_length=10)),
                ('room_type', models.CharField(choices=[('SINGLE ROOM', '1 Person'), ('DOUBLE ROOM', '2 peoples, 1 bed'), ('TWIN ROOM', '2 peoples, 2 separate beds'), ('TRIPLE ROOM', '3 peoples, 1 or 2 beds'), ('FAMILY ROOM', '4 or more people, multiple beds')], default='', max_length=150)),
                ('trip_interest', models.CharField(choices=[('MUST SEE ATTRACTIONS', 'Must see attractions'), ('BEACH', 'Beach'), ('LOCAL CULTURE', 'Local culture'), ('WELLNESS & SPA', 'Wellness and spa'), ('BIRD WATCHING', 'Bird Watching'), ('BIKING', 'Biking'), ('SCUBA DIVING', 'Scuba diving'), ('SNORKELING', 'Snorkeling'), ('TREKKING', 'Trekking'), ('SURF', 'Surf'), ('KITE-SURF', 'Kite-surf'), ('HISTORY', 'History')], default='', max_length=50)),
                ('trip_reason', models.CharField(choices=[('FRIEND', 'Friend trip'), ('ROAD', 'Road trip'), ('SOLO', 'Solo trip'), ('REUNION', 'Reunion'), ('ANNIVERSARY', 'Anniversary'), ('HONEYMOON', 'Honeymoon'), ('FAMILY', 'Family vacation')], default='', max_length=50)),
                ('custom_trip_reason', models.CharField(default='', max_length=50)),
                ('pax_type', models.CharField(help_text='Use colon to map pax code and their number in party', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Authenticated Operator Tour', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
