# Generated by Django 4.2.6 on 2023-10-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='traveler_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelers.travelergroup'),
        ),
    ]
