# Generated by Django 4.2.6 on 2023-10-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_traveler_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
