# Generated by Django 4.2.6 on 2023-11-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0004_traveler_created_at_alter_traveler_email'),
        ('orders', '0005_alter_orderstatus_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_creator',
            field=models.ManyToManyField(to='travelers.traveler'),
        ),
    ]
