# Generated by Django 4.2.6 on 2023-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_description_order_order_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
