# Generated by Django 4.2.6 on 2023-11-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_order_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_creator',
        ),
    ]
