# Generated by Django 4.2.6 on 2023-11-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0010_alter_traveler_lead_traveler'),
        ('orders', '0011_order_order_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='travelers.traveler'),
        ),
    ]
