# Generated by Django 4.2.6 on 2023-11-22 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_traveler_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='orders.order'),
        ),
    ]
