# Generated by Django 4.2.6 on 2023-11-30 17:34

import apps.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=apps.images.models.upload_to)),
                ('folder_name', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
            ],
        ),
    ]
