# Generated by Django 4.2.6 on 2023-12-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_hotel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='hotel_image',
            new_name='hotel_images',
        ),
    ]
