# Generated by Django 4.2.6 on 2023-12-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_supplier_contacts'),
        ('images', '0004_rename_hotel_image_image_hotel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='supplier_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_images', to='suppliers.supplier'),
        ),
    ]
