version: "3.9"

services:
  backend:
    build: . 
    image: pereepl_app:v1
    command: python /apps/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "3951:8000"
    depends_on:
      - backend_pg_db

  backend_pg_db:
    image: postgres:14
    container_name: backend_pereepl_pg_db
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5731:5432"
      
volumes:
  pg_data:
    external: false



# version: '3.9'
# services:
#   postgres_db:
#     image: postgres:14
#     container_name: pg_pereepl_db
#     restart: always
#     env_file:
#       - .env
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#     ports:
#       - "5731:5432"

# volumes:
#   pg_data:
#     external: false
    
