version: "3.9"

services:
  backend:
    build: . 
    image: pereepl_app:v1
    command: python /apps/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/apps
    ports:
      - "3951:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: backend_pereepl_pg_db
    restart: always
    env_file:
      - ./.env.dev

    volumes:
      - pg_data:/var/lib/postgresql/data
      
volumes:
  pg_data:
    external: false