# Generated by Django 4.2.6 on 2023-12-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(null=True, verbose_name='expires_at'),
        ),
    ]
