# Generated by Django 4.2.6 on 2023-11-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='location',
            new_name='locations',
        ),
    ]
