# Generated by Django 4.2.6 on 2023-11-28 17:31

import apps.hotels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_created_at_hotel_updated_at'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='hotel',
        #     name='image_url',
        #     field=models.ImageField(blank=True, null=True, upload_to=apps.hotels.models.upload_to),
        # ),
        migrations.AlterField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
