# Generated by Django 4.2.6 on 2023-11-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_image_url_alter_hotel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_name',
            field=models.CharField(default='<function uuid4 at 0x7ffaace029e0>', max_length=255, unique=True),
        ),
    ]
