# Generated by Django 4.2.6 on 2023-11-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_hotel_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image_name',
        ),
    ]
