# Generated by Django 4.2.6 on 2023-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_fname_image_file_name_and_more'),
        ('hotels', '0013_alter_hotel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=models.ManyToManyField(blank=True, to='images.image'),
        ),
    ]
