# Generated by Django 4.2.6 on 2023-12-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_hotel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='images',
        ),
    ]
