# Generated by Django 4.2.6 on 2023-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('role', models.CharField(choices=[('RESERVATION', 'Reservation'), ('MANAGER', 'Manager'), ('RESPONSIBLE', 'Responsible'), ('CORPORATE', 'Corporate')], default='Reservation', max_length=255)),
            ],
        ),
    ]
