from apps.orders.views import OrderViewset
from apps.searches.views import SearchListView
from apps.suppliers.views import SupplierViewSet
from apps.hotels.views import HotelViewset
from apps.itineraries.views import ItineraryViewSet
from apps.activities.views import ActivityViewset
from apps.users.views import UserViewset
from apps.images.views import ImageViewset
from apps.subscriptions.views import PlanViewset