# Generated by Django 4.2.6 on 2023-11-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('activities', '0001_initial'),
        ('mada_countries', '0003_geographicalcoordinate_remove_madacountry_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItinerarySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
                ('activities', models.ManyToManyField(to='activities.activity')),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_locations_set', to='mada_countries.madacountry')),
                ('hotels', models.ManyToManyField(to='hotels.hotel')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_locations_set', to='mada_countries.madacountry')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('segments', models.ManyToManyField(to='itineraries.itinerarysegment')),
            ],
        ),
    ]
