# Generated by Django 4.2.6 on 2023-11-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='availability',
            field=models.TextField(null=True),
        ),
    ]
