# Generated by Django 4.2.6 on 2023-11-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_itinerary_clients_itinerary_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='clients',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='orders',
            new_name='order',
        ),
    ]
