# Generated by Django 4.2.6 on 2023-11-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_rename_clients_itinerary_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
