# Generated by Django 4.2.6 on 2023-11-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_itinerary_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='created_at',
        ),
    ]
