# Generated by Django 4.2.6 on 2023-11-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0010_itinerary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
