# Generated by Django 4.2.6 on 2023-12-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='client',
            new_name='user',
        ),
    ]
