# Generated by Django 4.2.6 on 2023-12-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_client_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
