# Generated by Django 4.2.6 on 2023-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(null=True)),
                ('billing_address', models.TextField()),
                ('type', models.CharField(max_length=50, null=True)),
                ('area_covered', models.CharField(max_length=255, null=True)),
                ('remark', models.TextField()),
                ('contact', models.ManyToManyField(blank=True, null=True, to='contacts.contact')),
            ],
        ),
    ]
