# Generated by Django 4.2.6 on 2023-11-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='contact',
            new_name='contacts',
        ),
    ]
