# Generated by Django 4.2.6 on 2023-11-12 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MadaCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('international_name', models.CharField(db_index=True, max_length=255)),
                ('country_code', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=15, null=True)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=15, null=True)),
                ('user', models.ForeignKey(help_text='Authenticated Operator Tour', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
