# Generated by Django 4.2.6 on 2023-11-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mada_countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madacountry',
            name='international_name',
        ),
        migrations.AddField(
            model_name='madacountry',
            name='district',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='madacountry',
            name='province',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='madacountry',
            name='region',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='madacountry',
            name='country_code',
            field=models.CharField(db_index=True, default='MDG', max_length=255),
        ),
    ]
