# Generated by Django 4.2.6 on 2023-11-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mada_countries', '0002_remove_madacountry_international_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicalCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=15, null=True)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='madacountry',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='madacountry',
            name='longitude',
        ),
        migrations.AddField(
            model_name='madacountry',
            name='commune',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='madacountry',
            name='geographical_coordinates',
            field=models.ManyToManyField(to='mada_countries.geographicalcoordinate'),
        ),
    ]
