# Generated by Django 4.2.6 on 2023-10-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
