# Generated by Django 4.2.6 on 2023-11-06 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travelers', '0002_alter_traveler_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='user',
            field=models.ForeignKey(help_text='Authenticated Operator Tour', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
