# Generated by Django 4.2.6 on 2023-11-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0003_traveler_user_alter_traveler_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
