# Generated by Django 4.2.6 on 2023-11-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0004_traveler_created_at_alter_traveler_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelergroup',
            old_name='travelers',
            new_name='travelersGroup',
        ),
    ]
