# Generated by Django 4.2.6 on 2023-11-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0005_rename_travelers_travelergroup_travelersgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelergroup',
            old_name='travelersGroup',
            new_name='travelers',
        ),
    ]
