# Generated by Django 4.2.6 on 2023-11-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0006_rename_travelersgroup_travelergroup_travelers'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='traveler_type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
