# Generated by Django 4.2.6 on 2023-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0007_traveler_traveler_type_alter_traveler_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelergroup',
            name='number_in_party',
            field=models.IntegerField(null=True),
        ),
    ]
