# Generated by Django 4.2.6 on 2023-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0008_travelergroup_number_in_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='first_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='last_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
