# Generated by Django 4.2.6 on 2023-11-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0009_alter_traveler_email_alter_traveler_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='lead_traveler',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
