# Generated by Django 4.2.6 on 2023-11-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0010_alter_traveler_lead_traveler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('UNK', 'Unknown')], max_length=10),
        ),
    ]
