# Generated by Django 4.2.6 on 2023-11-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_room_number_roomprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
