# Generated by Django 4.2.6 on 2023-11-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_title_activity_name_activity_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='location',
            new_name='locations',
        ),
    ]
