# Generated by Django 4.2.6 on 2023-11-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_rename_location_activity_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='locations',
            new_name='location',
        ),
    ]
