# Generated by Django 4.2.6 on 2023-11-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_created_at_activity_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
